book:
    path: /
    defaults: { _controller: BookkeeperManagerBundle:Default:index }

book_show:
  path: /show/{id}
  defaults: { _controller: BookkeeperManagerBundle:Default:show }

book_new:
  path: /new
  defaults: { _controller: BookkeeperManagerBundle:Default:new }

book_create:
  path: /create
  defaults: { _controller: BookkeeperManagerBundle:Default:new }
  requirements: { _method: post }

book_edit:
  path: /edit/{id}
  defaults: { _controller: BookkeeperManagerBundle:Default:edit }

book_update:
  path: /update/{id}
  defaults: { _controller: BookkeeperManagerBundle:Default:update }
  requirements: {_method: post|put}

book_delete:
  path: /delete/{id}
  defaults: { _controller: BookkeeperManagerBundle:Default:delete }
  requirements: {_method: post|delete}