homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }

posts:
  path: /posts/
  defaults: { _controller: AppBundle:Note:getNotes }

post:
  path: /posts/{id}
  defaults: { _controller: AppBundle:Note:getNote }
  requirements: { id: \d+ }

post_create:
  path: /create
  defaults: { _controller: AppBundle:Note:createNote }
  requirements: { _method: post}

post_edit:
  path: /edit/{id}
  defaults: { _controller: AppBundle:Note:editNote}
  requirements: { _method: post, id: \d+ }

post_delete:
  path: /delete/{id}
  defaults: { _controller: AppBundle:Note:deleteNote}
  requirements: { _method: post|delete}

comment_create:
  path:  /comment/{noteId}
  defaults: { _controller: AppBundle:Comments:create }
  requirements: { _method: post, id: \d+}