homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }

posts:
  path: /posts/
  defaults: { _controller: AppBundle:Note:getNotes }

post:
  path: /posts/{id}
  defaults: { _controller: AppBundle:Note:getNote }

post_create:
  path: /create
  defaults: { _controller: AppBundle:Note:createNote }